- platform: foscam
  ip: !secret cam_garden
  username: !secret foscam_username
  password: !secret foscam_password
  name: Tuin
- platform: foscam
  ip: !secret cam_frontdoor
  username: !secret foscam_username
  password: !secret foscam_password
  name: Voordeur

- platform: mjpeg
  mjpeg_url: !secret octoprint_cam_url
  name: octaprint

- platform: generic
  name: doods_voordeur
  still_image_url: http://192.168.1.31:8123/local/doods_voordeur.jpg
- platform: generic
  name: doods_tuin
  still_image_url: http://192.168.1.31:8123/local/doods_tuin.jpg
  