- platform: foscam
  ip: !secret cam_garden
  username: !secret foscam_username
  password: !secret foscam_password
  name: Tuin
- platform: foscam
  ip: !secret cam_frontdoor
  username: !secret foscam_username
  password: !secret foscam_password
  name: Voordeur

- platform: mjpeg
  mjpeg_url: !secret octoprint_cam_url
  name: octaprint


