
- platform: template
  switches:
    frontdoor_motion:
      value_template: "{{is_state('sensor.frontdoor_motion_state', 'on')}}"
      turn_on:
        service: python_script.set_state
        data_template:
          entity_id: sensor.frontdoor_motion_state
          state: 'on'
      turn_off:
        service: python_script.set_state
        data_template:
          entity_id: sensor.frontdoor_motion_state
          state: 'off'
    backdoor_motion:
      value_template: "{{is_state('sensor.backdoor_motion_state', 'on')}}"
      turn_on:
        service: python_script.set_state
        data_template:
          entity_id: sensor.backdoor_motion_state
          state: 'on'
      turn_off:
        service: python_script.set_state
        data_template:
          entity_id: sensor.backdoor_motion_state
          state: 'off'

- platform: template
  switches:
    tv_livingroom:
      friendly_name: "TV woonkamer"
      value_template: "{{ is_state('binary_sensor.frontroomtelevision', 'on') }}"
      turn_on:
        - service: script.tv_on
      turn_off:
        - service: script.tv_off

- platform: template
  switches:
    auto_speaker_selection:
      friendly_name: "Automatische speaker selectie"
      value_template: "{{ is_state('sensor.auto_speaker_selection', 'on') }}"
      turn_on:
        service: python_script.set_state
        data_template:
          entity_id: sensor.auto_speaker_selection
          state: 'on'
      turn_off:
        service: python_script.set_state
        data_template:
          entity_id: sensor.auto_speaker_selection
          state: 'off'