- platform: ping
  name: frontroomtelevision
  host: !secret tv_woonkamer
  scan_interval: 30

- platform: template
  sensors:
    external_ip_diff:
      friendly_name: External IP Diff
      value_template: "{{(states.sensor.external_ip.state) == (states.sensor.vpn_digitalforensic_nl.state)}}"
    wasmachine_state:
      friendly_name: Wasmachine Status
      value_template: "{{states('sensor.wasmachine_current')|float > 0.0 }}"
      icon_template: >-
          {% if is_state("binary_sensor.wasmachine_state", "on") %}
            mdi:washing-machine
          {% else %}
            mdi:washing-machine-off
          {% endif %}

- platform: template
  sensors:
    forked_daapd_is_playing:
      value_template: '{% if states.media_player.forked_daapd_server.state == "playing" %}on{% else %}off{% endif %}'
      friendly_name: Forked daapd is active
    san_alarm_state:
      value_template: '{{(((state_attr("sensor.in2013_next_alarm", "Time in Milliseconds")| int / 1000) + 0*60) | timestamp_custom("%Y-%m-%d %H:%M:00")) == ((as_timestamp(now())+ (0) | int) + 0*60) | timestamp_custom("%Y-%m-%d %H:%M:00")}}'
      friendly_name: Sander Alarm status
    laris_alarm_state:
      value_template: '{{(((state_attr("sensor.oneplus_a6003_next_alarm", "Time in Milliseconds")| int / 1000) + 0*60) | timestamp_custom("%Y-%m-%d %H:%M:00")) == ((as_timestamp(now())+ (0) | int) + 0*60) | timestamp_custom("%Y-%m-%d %H:%M:00")}}'
      friendly_name: Larissa Alarm status
