- alias: 'Time: Toggle wakup light san'
  trigger:
  - platform: state
    entity_id: binary_sensor.san_alarm_state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: switch.slaapkamer_sand_switch
      state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.slaapkamer_sand_switch
  id: cc885961f59f490ca93d23a4d9a123213e8a7

- alias: 'Time: Toggle wakup light laris'
  trigger:
  - platform: state
    entity_id: binary_sensor.laris_alarm_state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: switch.slaapkamer_lari_switch
      state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.slaapkamer_lari_switch
  id: cc885961f59f4908439021ca93d23a4d9a123213e8a7
