- id: 2b365fd0862d4bc6a6b041cb6a237570
  alias: 'Security: Trigger alarm while armed away'
  trigger:
  - entity_id: group.deur_sensors_gang
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: group.motion_woonkamer
    for: '10'
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: armed_away
  action:
  - entity_id: alarm_control_panel.ha_alarm
    service: alarm_control_panel.alarm_trigger
- id: 5cc94c0074004f5cbbfd461a72fa3bd1
  alias: 'Security: Trigger alarm while armed at night'
  trigger:
  - entity_id: binary_sensor.voordeur_contact
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: group.motion_woonkamer
    for: '10'
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: armed_home
  action:
  - data: {}
    entity_id: alarm_control_panel.ha_alarm
    service: alarm_control_panel.alarm_trigger
- id: 640e1525c8044f88884242d54e3fbdbd
  alias: 'Security: Send notification when alarm triggered'
  trigger:
  - entity_id: alarm_control_panel.ha_alarm
    platform: state
    to: triggered
  action:
  - data:
      message: ALARM! The alarm has been triggered
    service: notify.telegram_home
