- id: 2b365fd0862d4bc6a6b041cb6a237570
  alias: Trigger alarm while armed away
  trigger:
  - entity_id: group.deur_sensors_gang
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: group.motion_woonkamer
    for: '10'
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: armed_away
  action:
  - entity_id: alarm_control_panel.ha_alarm
    service: alarm_control_panel.alarm_trigger
- id: 5cc94c0074004f5cbbfd461a72fa3bd1
  alias: Trigger alarm while armed at night
  trigger:
  - entity_id: binary_sensor.voordeur_contact
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: group.motion_woonkamer
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: armed_home
  action:
  - data: {}
    entity_id: alarm_control_panel.ha_alarm
    service: alarm_control_panel.alarm_trigger
- id: 640e1525c8044f88884242d54e3fbdbd
  alias: Send notification when alarm triggered
  trigger:
  - entity_id: alarm_control_panel.ha_alarm
    platform: state
    to: triggered
  action:
  - data:
      message: ALARM! The alarm has been triggered
    service: notify.telegram_home
- alias: anet a8 smoke detector
  trigger:
    platform: state
    entity_id: binary_sensor.anet_a8_rookmelder_smoke
    to: 'on'
  action:
  - service: notify.telegram_home
    data:
      message: Er is rook gedetecteerd bij de printer!!
      title: ''
  - service: notify.telegram_home
    data:
      message: ''
      data:
        photo:
          file: /config/www/img/smoke_alarm.jpg
  - service: tts.google_translate_say
    data:
      entity_id:
      - media_player.google_home_slaapkamer
      message: There is an smoke problem with the printer
      language: en
  - service: homeassistant.turn_off
    entity_id: switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch
  id: d13e03fda6ee4df0ae9e23f2599c6ffb