- alias: 'System: update dns record transip'
  trigger:
  - platform: time_pattern
    minutes: /01
    seconds: 1
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.external_ip_diff
      state: 'off'
    - condition: template
      value_template: '{{states.sensor.external_ip.state != Onbekend}}'
  action:
  - service: script.update_transip
  id: c85f1e5b262b4a78878701e5f3007872

- alias: 'Wakeup: Wake Me Up'
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == strptime(states.sensor.alarm_time.state,
      "%H:%M").strftime("%H:%M")}}'
  condition:
    condition: or
    conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.alarmstatus
        state: 'on'
      - condition: state
        entity_id: input_boolean.alarmweekday
        state: 'on'
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        - sun
    - condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.alarmstatus
        state: 'on'
      - condition: state
        entity_id: input_boolean.alarmweekday
        state: 'off'
  action:
  - service: script.start_spotify_wekker
  - service: homeassistant.turn_on
    entity_id: switch.slaapkamer_sand_switch
  - delay: 00:01:00
  - service: shell_command.speaker_google_home_slaapkamer_volume_up
    data:
      forked_daapd_serverip_port_ip: !secret forked_daapd_serverip_port_ip
  - delay: 00:01:00
  - service: shell_command.speaker_google_home_slaapkamer_volume_up
    data:
      forked_daapd_serverip_port_ip: !secret forked_daapd_serverip_port_ip
  - delay: 00:01:00
  - service: shell_command.speaker_google_home_slaapkamer_volume_up
    data:
      forked_daapd_serverip_port_ip: !secret forked_daapd_serverip_port_ip
  - delay: 00:01:00
  - service: shell_command.speaker_google_home_slaapkamer_volume_up
    data:
      forked_daapd_serverip_port_ip: !secret forked_daapd_serverip_port_ip
  - delay: 00:01:00
  - service: shell_command.speaker_google_home_slaapkamer_volume_up
    data:
      forked_daapd_serverip_port_ip: !secret forked_daapd_serverip_port_ip
  - delay: 00:01:00
  - service: shell_command.speaker_google_home_slaapkamer_volume_up
    data:
      forked_daapd_serverip_port_ip: !secret forked_daapd_serverip_port_ip
  - service: notify.telegram_home
    data:
      message: Good morning. Time to Wake Up!
      title: ''
  id: e29f11e00cce4118ab39decaadac6d4f

- id: '1625579108125'
  alias: 'Sensor: Doorbell - Notify avond'
  description: ''
  condition:
  - condition: and
    conditions:
    - condition: time
  # At least one of the following is required.
      after: "20:00:00"
      before: "07:00:00"
  use_blueprint:
    path: seamus65/doorbell-notify-alexa-and-or-google-and-send-camera-snapshot-to-app.yaml
    input:
      notification_message: Er wordt aangebeld!
      doorbell: binary_sensor.front_doorbell_doorbell
      google_device: media_player.deurbel_avond
      message: Er is iemand aan de deur!
      camera: camera.amcrest_camera
      notify_device: 4f6f4bcfa03849239d6429f4a8535afc
      notification_title: Er wordt aangebeld!
      delay: '00:00:01'

- id: '16255791081252'
  alias: 'Sensor: Doorbell - Notify overdag'
  description: ''
  condition:
  - condition: and
    conditions:
    - condition: time
  # At least one of the following is required.
      after: "07:00:00"
      before: "20:00:00"
  use_blueprint:
    path: seamus65/doorbell-notify-alexa-and-or-google-and-send-camera-snapshot-to-app.yaml
    input:
      notification_message: Er wordt aangebeld!
      doorbell: binary_sensor.front_doorbell_doorbell
      google_device: media_player.deurbel_overdag
      message: Er is iemand aan de deur!
      camera: camera.amcrest_camera
      notify_device: 4f6f4bcfa03849239d6429f4a8535afc
      notification_title: Er wordt aangebeld!
      delay: '00:00:01'
