- alias: 'Camera: camera_cast_select_voordeur'
  trigger:
    platform: state
    entity_id: input_select.camera_cast_select
    to: Voordeur
  action:
  - service: media_player.play_media
    entity_id:
    - media_player.woonkamer_hub
    data_template:
      media_content_id: '{{states("variable.frontdoor_pic_url")}}'
      media_content_type: image/jpg
  id: d7fa39f2356d4a4f9da208ea625b420c
- alias: 'Camera: camera_cast_select_tuin'
  trigger:
    platform: state
    entity_id: input_select.camera_cast_select
    to: Tuin
  action:
  - service: camera.play_stream
    data:
      entity_id: camera.tuin
      media_player: media_player.chromecast_woonkamer
  id: 2628e7239f0c4085827d6ab092bf2f43
- alias: 'Camera: camera_cast_select_baby'
  trigger:
    platform: state
    entity_id: input_select.camera_cast_select
    to: Babykamer
  action:
  - service: camera.play_stream
    data:
      entity_id: camera.babykamer
      media_player: media_player.chromecast_woonkamer
  id: a0e1c4d27a8549cab8e44ab6aedbbe91
  
- alias: 'Camera: send pic on ttgo_motion_dark'
  trigger:
  - entity_id: binary_sensor.ttgo_doorbell_pir
    platform: state
    to: 'on'
    for:
      seconds: 5
  condition:
    condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      value_template: '{{ now().strftime("%Y-%m-%d_%H.%M") }}_1.jpg'
      variable: frontdoor_pic_name
    service: variable.set_variable
  - data:
      value_template: >
        {% set url = states('input_text.base_url') %}
        {% set cam_folder = '/local/cam_captures/' %}
        {% set picname = states('variable.frontdoor_pic_name') %}
        {{[url,cam_folder,picname]|join}}
      variable: frontdoor_pic_url
    service: variable.set_variable
  - data:
      entity_id: camera.voordeur
      filename: /config/www/cam_captures/{{ states('variable.frontdoor_pic_name')}}
    service: camera.snapshot
  - data:
      message: Motion frontdoor
    service: notify.telegram_home
  - data:
      data:
        photo:
          file: /config/www/cam_captures/{{ states('variable.frontdoor_pic_name')}}
      message: Motion Frontdoor
    service: notify.telegram_home
  - delay: 00:00:02
  - data:
      entity_id: camera.voordeur
      filename: /config/www/cam_captures/{{ now().strftime("%Y-%m-%d_%H.%M") }}_2.jpg
    service: camera.snapshot
  - delay: 00:00:02
  - data:
      data:
        photo:
          file: /config/www/cam_captures/{{ now().strftime("%Y-%m-%d_%H.%M") }}_2.jpg
      message: Motion frontdoor
    service: notify.telegram_home
  id: 1e324f4bbcc8418a8241b694ad70e529
- alias: 'Camera: send pic on ttgo_motion_light'
  trigger:
  - entity_id: binary_sensor.ttgo_doorbell_pir
    platform: state
    to: 'on'
    for:
      seconds: 5
  condition:
    condition: state
    entity_id: sun.sun
    state: above_horizon
  action:
  - data:
      value_template: '{{ now().strftime("%Y-%m-%d_%H.%M") }}_1.jpg'
      variable: frontdoor_pic_name
    service: variable.set_variable
  - data:
      value_template: >
        {% set url = states('input_text.base_url') %}
        {% set cam_folder = '/local/cam_captures/' %}
        {% set picname = states('variable.frontdoor_pic_name') %}
        {{[url,cam_folder,picname]|join}}
      variable: frontdoor_pic_url
    service: variable.set_variable
  - data:
      entity_id: camera.voordeur
      filename: /config/www/cam_captures/{{ states('variable.frontdoor_pic_name')}}
    service: camera.snapshot
  - data:
      message: Motion frontdoor
    service: notify.telegram_home
  - data:
      data:
        photo:
          file: /config/www/cam_captures/{{ states('variable.frontdoor_pic_name')}}
      message: Motion Frontdoor
    service: notify.telegram_home
  - delay: 00:00:02
  - data:
      entity_id: camera.voordeur
      filename: /config/www/cam_captures/{{ now().strftime("%Y-%m-%d_%H.%M") }}_2.jpg
    service: camera.snapshot
  - delay: 00:00:02
  - data:
      data:
        photo:
          file: /config/www/cam_captures/{{ now().strftime("%Y-%m-%d_%H.%M") }}_2.jpg
      message: Motion frontdoor
    service: notify.telegram_home
  id: 93aede1794354ee5a6ad6eea8d980455
- id: 10677f69ff0b4c1faafffa18960974ae
  alias: 'Camera: send pic on ttgo doorbell_overdag'
  trigger:
  - entity_id: binary_sensor.ttgo_doorbell_button
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: '8:00'
    before: '19:00'
    condition: time
  action:
  - data:
      value_template: '{{ now().strftime("%Y-%m-%d_%H.%M") }}_1.jpg'
      variable: frontdoor_pic_name
    service: variable.set_variable
  - data:
      value_template: >
        {% set url = states('input_text.base_url') %}
        {% set cam_folder = '/local/cam_captures/' %}
        {% set picname = states('variable.frontdoor_pic_name') %}
        {{[url,cam_folder,picname]|join}}
      variable: frontdoor_pic_url
    service: variable.set_variable
  - data:
      entity_id: camera.voordeur
      filename: /config/www/cam_captures/{{ states('variable.frontdoor_pic_name')}}
    service: camera.snapshot
  - service: homeassistant.turn_on
    entity_id: switch.doorbellringswitch
  - data:
      message: Er wordt aangebeld
    service: notify.telegram_home
  - data_template:
      media_content_id: '{{states(''variable.frontdoor_pic_url'')}}'
      media_content_type: image/jpg
    entity_id:
    - media_player.woonkamer_hub
    service: media_player.play_media
  - data:
      data:
        photo:
          file: /config/www/cam_captures/{{ states('variable.frontdoor_pic_name')}}
      message: Er wordt aangebeld
    service: notify.telegram_home
  - delay: 00:00:02
  - data:
      entity_id: camera.voordeur
      filename: /config/www/cam_captures/{{ now().strftime("%Y-%m-%d_%H.%M") }}_2.jpg
    service: camera.snapshot
  - delay: 00:00:02
  - data:
      data:
        photo:
          file: /config/www/cam_captures/{{ now().strftime("%Y-%m-%d_%H.%M") }}_2.jpg
      message: Er wordt aangebeld
    service: notify.telegram_home
  - delay: 00:00:15
  - entity_id:
    - media_player.woonkamer_hub
    service: media_player.turn_off
- id: 10677f69ff0b4c1faafffa18960974afeeeee
  alias: 'Camera: send pic on ttgo doorbell_avond'
  trigger:
  - entity_id: binary_sensor.ttgo_doorbell_button
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: '19:00'
    before: 08:00
    condition: time
  action:
  - data:
      value_template: '{{ now().strftime("%Y-%m-%d_%H.%M") }}_1.jpg'
      variable: frontdoor_pic_name
    service: variable.set_variable
  - data:
      value_template: >
        {% set url = states('input_text.base_url') %}
        {% set cam_folder = '/local/cam_captures/' %}
        {% set picname = states('variable.frontdoor_pic_name') %}
        {{[url,cam_folder,picname]|join}}
      variable: frontdoor_pic_url
    service: variable.set_variable
  - data:
      entity_id: camera.voordeur
      filename: /config/www/cam_captures/{{ states('variable.frontdoor_pic_name')}}
    service: camera.snapshot
  - data:
      message: Er wordt aangebeld
    service: notify.telegram_home
  - data_template:
      media_content_id: '{{states(''variable.frontdoor_pic_url'')}}'
      media_content_type: image/jpg
    entity_id:
    - media_player.woonkamer_hub
    service: media_player.play_media
  - data:
      data:
        photo:
          file: /config/www/cam_captures/{{ states('variable.frontdoor_pic_name')}}
      message: Er wordt aangebeld
    service: notify.telegram_home
  - delay: 00:00:02
  - data:
      entity_id: camera.voordeur
      filename: /config/www/cam_captures/{{ now().strftime("%Y-%m-%d_%H.%M") }}_2.jpg
    service: camera.snapshot
  - delay: 00:00:02
  - data:
      data:
        photo:
          file: /config/www/cam_captures/{{ now().strftime("%Y-%m-%d_%H.%M") }}_2.jpg
      message: Er wordt aangebeld
    service: notify.telegram_home
  - delay: 00:00:15
  - entity_id:
    - media_player.woonkamer_hub
    service: media_player.turn_off
- alias: 'Camera: send picture on doorbell'
  trigger:
    platform: state
    entity_id: binary_sensor.deurbel_sensor_2
    from: 'on'
    to: 'off'
  action:
  - service: variable.set_variable
    data:
      variable: frontdoor_pic_name
      value_template: '{{ now().strftime("%Y-%m-%d_%H.%M") }}_1.jpg'
  - service: variable.set_variable
    data:
      variable: frontdoor_pic_url
      value_template: >
        {% set url = states('input_text.base_url') %}
        {% set cam_folder = '/local/cam_captures/' %}
        {% set picname = states('variable.frontdoor_pic_name') %}
        {{[url,cam_folder,picname]|join}}
  - service: camera.snapshot
    data:
      entity_id: camera.voordeur
      filename: /config/www/cam_captures/{{ states('variable.frontdoor_pic_name')}}
  - service: notify.telegram_home
    data:
      message: Er wordt aangebeld
  - service: tts.google_translate_say
    data:
      entity_id:
      - media_player.google_home_woonkamer
      message: Somebody is ringing the doorbell
      language: en
  - delay: 00:00:03
  - service: media_player.play_media
    entity_id:
    - media_player.woonkamer_hub
    data_template:
      media_content_id: '{{states(''variable.frontdoor_pic_url'')}}'
      media_content_type: image/jpg
  - service: notify.telegram_home
    data:
      message: Er wordt aangebeld
      data:
        photo:
          file: /config/www/cam_captures/{{ states('variable.frontdoor_pic_name')}}
  - delay: 00:00:02
  - service: camera.snapshot
    data:
      entity_id: camera.voordeur
      filename: /config/www/cam_captures/{{ now().strftime("%Y-%m-%d_%H.%M") }}_2.jpg
  - delay: 00:00:02
  - service: notify.telegram_home
    data:
      message: Er wordt aangebeld
      data:
        photo:
          file: /config/www/cam_captures/{{ now().strftime("%Y-%m-%d_%H.%M") }}_2.jpg
  - delay: 00:00:15
  - service: media_player.turn_off
    entity_id:
    - media_player.woonkamer_hub
  id: 1bd671eb9d354097acf2d29c539724e4
- id: '1582840785346'
  alias: 'Camera: motion_ttgo_doorbell'
  description: ''
  trigger:
  - device_id: e2c4ed7b00a441008f4c9fd9d58496c6
    domain: binary_sensor
    entity_id: binary_sensor.ttgo_doorbell_pir
    platform: device
    type: motion
  condition: []
  action:
  - data:
      value: Klik rechts!
      variable: doorbell_text
    service: variable.set_variable
- id: '1583022507045'
  alias: 'Camera: motion text reset ttgo doorbell'
  description: ''
  trigger:
  - device_id: e2c4ed7b00a441008f4c9fd9d58496c6
    domain: binary_sensor
    entity_id: binary_sensor.ttgo_doorbell_pir
    for:
      hours: 0
      minutes: 0
      seconds: 10
    platform: device
    type: no_motion
  condition: []
  action:
  - data:
      value: ''
      variable: doorbell_text
    service: variable.set_variable
- id: edc6e89ca14b4fd99d477323fa3e3c7e
  alias: 'Camera: webhook endpoint to motion backdoor nas'
  trigger:
  - platform: webhook
    webhook_id: motion_backdoor
  condition:
  - condition: state
    entity_id: sensor.backdoor_motion_state
    state: 'on'
  action:
  - data:
      value_template: '{{ now().strftime("%Y-%m-%d_%H.%M") }}_1.jpg'
      variable: garden_pic_name
    service: variable.set_variable
  - data:
      value_template: >
        {% set url = states('input_text.base_url') %}
        {% set cam_folder = '/local/cam_captures/' %}
        {% set picname = states('variable.frontdoor_pic_name') %}
        {{[url,cam_folder,picname]|join}}
      variable: garden_pic_url
    service: variable.set_variable
  - data:
      entity_id: camera.tuin
      filename: /config/www/cam_captures/{{ states('variable.garden_pic_name')}}
    service: camera.snapshot
  - data:
      data:
        photo:
          file: /config/www/cam_captures/{{ states('variable.garden_pic_name')}}
      message: ''
    service: notify.telegram_home
  - data:
      message: Beweging gedetecteerd tuin
      title: ''
    service: notify.telegram_home
- id: f104953f047d423c8bdf62aa1bc66ad9
  alias: 'Camera: Webhook endpoint to motion frontdoor nas'
  trigger:
  - platform: webhook
    webhook_id: motion_entrance
  condition:
  - condition: state
    entity_id: sensor.frontdoor_motion_state
    state: 'on'
  action:
  - data:
      value_template: '{{ now().strftime("%Y-%m-%d_%H.%M") }}_1.jpg'
      variable: frontdoor_pic_name
    service: variable.set_variable
  - data:
      value_template: >
        {% set url = states('input_text.base_url') %}
        {% set cam_folder = '/local/cam_captures/' %}
        {% set picname = states('variable.frontdoor_pic_name') %}
        {{[url,cam_folder,picname]|join}}
      variable: frontdoor_pic_url
    service: variable.set_variable
  - data:
      entity_id: camera.voordeur
      filename: /config/www/cam_captures/{{ states('variable.frontdoor_pic_name')}}
    service: camera.snapshot
  - data:
      data:
        photo:
          file: /config/www/cam_captures/{{ states('variable.frontdoor_pic_name')}}
      message: ''
    service: notify.telegram_home
  - data:
      message: Beweging gedetecteerd voordeur
      title: ''
    service: notify.telegram_home