- alias: message if octoprint finished
  trigger:
  - platform: numeric_state
    entity_id: sensor.octoprint_job_percentage
    above: 99
  action:
  - service: notify.telegram_home
    data:
      message: Printer is bijna klaar
  id: c70b29b3e4fc408a801dc4360d2a082d