- alias: 'Octoprint: message if octoprint finished'
  trigger:
  - platform: numeric_state
    entity_id: sensor.octoprint_job_percentage
    above: 99
  action:
  - service: notify.telegram_home
    data:
      message: Printer is bijna klaar
  id: c70b29b3e4fc408a801dc4360d2a082d
- alias: 'Octoprint: anet a8 smoke detector'
  trigger:
    platform: state
    entity_id: binary_sensor.anet_a8_rookmelder_smoke
    to: 'on'
  action:
  - service: notify.telegram_home
    data:
      message: Er is rook gedetecteerd bij de printer!!
      title: ''
  - service: notify.telegram_home
    data:
      message: ''
      data:
        photo:
          file: /config/www/img/smoke_alarm.jpg
  - service: tts.google_translate_say
    data:
      entity_id:
      - media_player.google_home_slaapkamer
      message: There is an smoke problem with the printer
      language: en
  - service: homeassistant.turn_off
    entity_id: switch.anet_a8
  id: d13e03fda6ee4df0ae9e23f2599c6ffb

- alias: 'Octoprint: anet a8 job 100% shutdown'
  id: d13e03fda6ee4df0ae9e23f2599c6ffb12111
  trigger:
    platform: numeric_state
    entity_id: sensor.octoprint_job_percentage
    above: 99
    for: 01:00:00
  action:
  - service: homeassistant.turn_off
    entity_id: switch.anet_a8