- alias: 'Motion: switch toilet beneden'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_wc_beneden_occupancy
    to: 'on'
  condition:
    condition: state
    entity_id: light.wc_beneden_light
    state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: light.wc_beneden_light
  id: 89e5366481024451a9bc4a1595bdad3712312

- alias: 'Motion: switch toilet beneden off after 5 min.'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_wc_beneden_occupancy
    for: 00:05:00
    to: 'off'
  condition:
    condition: state
    entity_id: light.wc_beneden_light
    state: 'on'
  action:
  - service: homeassistant.turn_off
    entity_id: light.wc_beneden_light
  id: 89e5366481024451a9bc4a1595bdad371231211

- alias: 'Motion: Switch gang lampen'
  trigger:
    platform: numeric_state
    entity_id: sensor.beweging_gang_burglar
    above: '7'
  action:
  - service: homeassistant.turn_on
    entity_id: light.gang_lampen
  id: 89e5366481024451a9bc4a1595bdad37

- id: c1637d730d7046a4b4d5db25f46924d0
  alias: 'Motion: Turn off light 10 minutes after last movement gang'
  trigger:
  - below: '1'
    entity_id: sensor.beweging_gang_burglar
    for: 0:10:00
    platform: numeric_state
  action:
  - entity_id: light.gang_lampen
    service: homeassistant.turn_off
- alias: 'Motion: trigger_ligts_motion_frontdoor_10_minutes'
  trigger:
  - platform: state
    entity_id: sensor.motion_frontdoor_activated
    to: 'on'
    for:
      minutes: 10
  condition:
    condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: python_script.set_state
    data_template:
      entity_id: sensor.motion_frontdoor_activated
      state: 'off'
  id: 44f96dae236b4f82b6d9ad9858333f8e
- alias: 'Motion: trigger_lights_motion_door_living_room'
  trigger:
  - platform: state
    entity_id: group.deur_sensors_gang
  condition:
    condition: state
    entity_id: light.gang_beneden
    state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: light.gang_beneden
  id: be852e3d50464ae5bcf6b5210b7d2822

- alias: 'Motion: Turn on light gang_beneden on'
  trigger:
    platform: state
    entity_id: binary_sensor.beweging_gang_lux_occupancy
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: light.gang_beneden
  id: 52e93ae98b02425083e8082ac68ad71011
  
- alias: 'Motion: Turn off light 5 minutes after gang_beneden'
  trigger:
    platform: state
    entity_id: light.gang_beneden
    to: 'on'
    for:
      minutes: 5
  action:
  - service: homeassistant.turn_off
    entity_id: light.gang_beneden
  id: 52e93ae98b02425083e8082ac68ad710

- alias: 'Sensor: Wasmachine is klaar'
  trigger:
  - platform: state
    entity_id: binary_sensor.wasmachine_state
    to: 'off'
  action:
  - service: notify.telegram_home
    data:
      message: Wasmachine is klaar!!
  - service: notify.telegram_home
    data:
      message: ''
      data:
        photo:
          file: /config/www/img/wasmachine_done.jpg
  id: 87f2c7f85a54462383eb4de36a8f0b61
- alias: 'Sensor: Wasmachine gaat weer beginnen'
  trigger:
  - platform: state
    entity_id: binary_sensor.wasmachine_state
    to: 'on'
  action:
  - service: notify.telegram_home
    data:
      message: Wasmachine gaat er weer voor!
  - service: notify.telegram_home
    data:
      message: ''
      data:
        photo:
          file: /config/www/img/wasmachine_running.jpg
  id: f0975aeecfd24327841533146953a011
- id: 507b15c277b6455e8111071f9b5d4677
  alias: 'Motion: woonkamer motion lights'
  trigger:
  - entity_id: group.motion_woonkamer
    platform: state
    to: 'on'
  - entity_id: group.contacts_woonkamer
    platform: state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: light.woonkamer_spots
      state: 'off'
    - below: '30'
      condition: numeric_state
      entity_id: sensor.woonkamer_lux
  action:
  - entity_id: light.woonkamer_spots
    service: homeassistant.turn_on
- id: a643cf39bc2446f1872813b424d79a08
  alias: 'Motion: turn woonkamer spots off 30 minutes after last movement'
  trigger:
  - entity_id: group.motion_woonkamer
    for: 0:30:00
    platform: state
    to: 'off'
  - above: '100'
    entity_id: sensor.woonkamer_lux
    platform: numeric_state
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: light.woonkamer_spots
      state: 'on'
  action:
  - entity_id: light.woonkamer_spots
    service: homeassistant.turn_off
