- alias: 'Light: hue dimmer switch woonkamer_on'
  trigger:
    platform: state
    entity_id: sensor.hue_dimmer_switch_woonkamer_action
    to: on-press
  condition:
    condition: state
    entity_id: light.tafellamp_1
    state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: light.living_room
  id: f17c609eb2eb44f0bd69c2ec28d5117c
- alias: 'Light: hue dimmer switch woonkamer_off'
  trigger:
    platform: state
    entity_id: sensor.hue_dimmer_switch_woonkamer_action
    to: off-press
  condition:
    condition: state
    entity_id: light.tafellamp_1
    state: 'on'
  action:
  - service: homeassistant.turn_off
    entity_id: light.living_room
  id: 4d34fbc3c72e43ed9904f42722dd07dd
- alias: 'Light: hue dimmer switch woonkamer_up'
  trigger:
    platform: state
    entity_id: sensor.hue_dimmer_switch_woonkamer_action
    to: up-press
  action:
  - service: homeassistant.turn_on
    entity_id: group.alle_keuken_lampen
  id: 7ff3205bbb25463bbae90fc389b8e49d
- alias: 'Light: hue dimmer switch woonkamer_down'
  trigger:
    platform: state
    entity_id: sensor.hue_dimmer_switch_woonkamer_action
    to: down-press
  action:
  - service: homeassistant.turn_off
    entity_id: group.alle_keuken_lampen
  id: 80d25f1e43d54d8e89912c5b5fb8d02e
- alias: 'Light: tradfri dimmer switch tuin_toggle'
  trigger:
    platform: state
    entity_id: sensor.tradfri_remote_action
    to: toggle
  action:
  - service: homeassistant.toggle
    entity_id: group.garden_lights
  id: 80d25f1e43d54d8e89912c5b5fb8d1232102e
- alias: 'Light: hue dimmer switch slaapkamer_on'
  trigger:
    platform: state
    entity_id: sensor.hue_dimmer_switch_slaapkamer_action
    to: on-press
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: switch.slaapkamer_rechts
      state: 'off'
    - condition: state
      entity_id: switch.slaapkamer_links
      state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: group.slaapkamer_lampen
  id: 083eed5368e34484b8195def69b4d5b9
- alias: 'Light: hue dimmer switch slaapkamer_off'
  trigger:
    platform: state
    entity_id: sensor.hue_dimmer_switch_slaapkamer_action
    to: off-press
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: switch.slaapkamer_rechts
      state: 'on'
    - condition: state
      entity_id: switch.slaapkamer_links
      state: 'on'
  action:
  - service: homeassistant.turn_off
    entity_id: group.slaapkamer_lampen
  id: 0df8213e6bf24b5d88e222703795e425
- alias: 'Light: hue dimmer switch slaapkamer_links_up_on'
  trigger:
    platform: state
    entity_id: sensor.hue_dimmer_switch_slaapkamer_action
    to: up-press
  condition:
    condition: state
    entity_id: switch.slaapkamer_links
    state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.slaapkamer_links
  id: 3ed08cc4962e4e4896fef19424b7189a
- alias: 'Light: hue dimmer switch slaapkamer_links_up_off'
  trigger:
    platform: state
    entity_id: sensor.hue_dimmer_switch_slaapkamer_action
    to: up-press
  condition:
    condition: state
    entity_id: switch.slaapkamer_links
    state: 'on'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.slaapkamer_links
  id: bf928ff9029a4a609e7148e9cbf335a8
- alias: 'Light: hue dimmer switch slaapkamer_rechts_up_on'
  trigger:
    platform: state
    entity_id: sensor.hue_dimmer_switch_slaapkamer_action
    to: down-press
  condition:
    condition: state
    entity_id: switch.slaapkamer_rechts
    state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.slaapkamer_rechts
  id: cdd234476ec946aeb5818cc44d463ac8
- alias: 'Light: hue dimmer switch slaapkamer_rechts_up_off'
  trigger:
    platform: state
    entity_id: sensor.hue_dimmer_switch_slaapkamer_action
    to: down-press
  condition:
    condition: state
    entity_id: switch.slaapkamer_rechts
    state: 'on'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.slaapkamer_rechts
  id: b5056446e2354ed6a038309fa47358ab

- alias: 'Switch: Denon AMP Channel TV'
  trigger:
    platform: state
    entity_id: input_select.amp_receiver_input
    to: TV
  action:
  - service: shell_command.amp_receiver_tv
    data:
      ip_denon_receiver_ip: !secret denon_receiver_ip
  id: e3edb396ff894311b9ba6b7da764415c
- alias: 'Switch: Denon AMP Channel Airplay'
  trigger:
    platform: state
    entity_id: input_select.amp_receiver_input
    to: Airplay
  action:
  - service: shell_command.amp_receiver_airplay
    data:
      ip_denon_receiver_ip: !secret denon_receiver_ip
  id: 8e80a7841ba84ce5bccc56514017a4ef

- alias: 'Switch: Denon AMP Power if Channel Airplay'
  trigger:
    platform: state
    entity_id: input_select.amp_receiver_input
    to: Airplay
  action:
  - entity_id: switch.denon_power
    service: homeassistant.turn_off
  id: 8e80a7841ba84ce5bccc56514017afdas4ef