- alias: toggle_kas_lamp
  trigger:
  - platform: time
    at: '10:00:00'
  - platform: time
    at: '22:00:00'
  action:
  - service: homeassistant.toggle
    entity_id: switch.kerstboom_switch
  id: cc885961f59f490ca93d23a4d9a3e8a7

- alias: Reset power / Gas variables / today_rain
  trigger:
    platform: time
    at: 01:30:00
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.midnight_power_consumption_low
      value: '{{ states.sensor.energy_consumption_tarif_1.state }}'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.midnight_power_production_low
      value: '{{ states.sensor.energy_production_tarif_1.state }}'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.midnight_power_consumption_normal
      value: '{{ states.sensor.energy_consumption_tarif_2.state }}'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.midnight_power_production_normal
      value: '{{ states.sensor.energy_production_tarif_2.state }}'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.midnight_gas_consumption
      value: '{{ states.sensor.gas_consumption.state }}'
  - service: python_script.set_state
    data_template:
      entity_id: sensor.today_rain_mm
      state: '{{0.0 | round(2)}}'
  id: f789f799896840bdbead2029cc536f85
